config/routes.rb
Rails.application.routes.draw do
  root :to => 'chapters#index'

  resources :chapters do
    resources :lessons
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :lessons
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :chapter
  validates :name, :presence => true
  validates :content, :presence => true

  def next
    @lesson = Lesson.find(:id)
    @nextlesson = @lesson.id + 1
    return @nextlesson
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      flash[:notice] = "Chapter successfully saved!"
      redirect_to chapters_path
    else
      render :new
    end
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def edit
    @chapter = Chapter.find(params[:id])
  end

  def update
    @chapter = Chapter.find(params[:id])
    if @chapter.update(chapter_params)
      flash[:notice] = "Chapter successfully updated!"
      redirect_to chapters_path
    else
      render :edit
    end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    if @chapter.destroy
      flash[:alert] = "Chapter successfully deleted!"
    end
    redirect_to chapters_path
  end

private
  def chapter_params
    params.require(:chapter).permit(:name)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = @chapter.lessons.new
  end

  def create
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = @chapter.lessons.new(lesson_params)
    if @lesson.save
      flash[:notice] = "Lesson successfully saved!"
      redirect_to chapter_path(@lesson.chapter)
    else
      render :new
    end
  end

  def edit
    @chapter = Chapter.find(params[:chapter_id])
    @lesson = @chapter.lessons.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      flash[:notice] = "Lesson successfully updated!"
      redirect_to chapter_path(@lesson.chapter)
    else
      render :edit
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
  if @lesson.destroy
    flash[:notice] = "Lesson deleted"
  end
    redirect_to chapter_path(@lesson.chapter)
  end

  def show
    @lesson = Lesson.find(params[:id])
    @chapter = Chapter.find(params[:chapter_id])
  end

  def next
    @lesson = Lesson.find(params[:id])
    @nextlesson = Lesson.find(params[:id = @lesson.id+1])
    return @nextlesson
  end

private
  def lesson_params
    params.require(:lesson).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= render "layouts/errors", :object => @chapter %>

<%= form_for @chapter do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus=>true %>
  <%= f.submit %>
<% end %>

app/views/chapters/edit.html.erb
<% content_for(:title, "Edit | Learn How") %>

<h1>Edit Chapter</h1>

<%= render 'form' %>

app/views/chapters/index.html.erb
<% content_for(:title, "Rails | Learn" ) %>

<h1>Chapters</h1>

<ul>
  <% @chapters.each do |chapter| %>
    <li><%= link_to chapter.name, chapter_path(chapter) %></li>
        <% end %>
</ul>

<%= link_to "Create New Chapter", new_chapter_path %>

app/views/chapters/new.html.erb
<% content_for(:title, "New | Learn How") %>

<h1>New Chapter!</h1>

<%= render 'form' %>

app/views/chapters/show.html.erb
<% content_for(:title, "Chapters | To Do") %>

<h1><%= @chapter.name %></h1>



<% if @chapter.lessons.any? %>
  <h4>Here are the lessons for this chapter:</h4>
  <ul>
  <% @chapter.lessons.each do |lesson| %>
      <li><%= link_to lesson.name, chapter_lesson_path(@chapter, lesson) %></li>
  <% end %>
  </ul>
<% else %>
  <p>There are no lessons yet!</p>
<% end %>


<div class="col-xs-12">
  <p><%= link_to "Add a lesson", new_chapter_lesson_path(@chapter) %></p>
  <p><%= link_to "Edit", edit_chapter_path %></p>
  <p><%= link_to "Delete", chapter_path(@chapter),
  :data => {:confirm => "You sure?",
            :method => "delete"} %></p>
  <p><%= link_to "Return to chapters", chapters_path %></p>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>  

<%= yield %>

</body>
</html>

app/views/lessons/_form.html.erb
<%= render 'layouts/errors', :object => @lesson %>

<%= form_for [@chapter, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<% content_for(:title, "Edit | Task") %>

<h1>Edit Task</h1>

<%= render 'form' %>

app/views/lessons/new.html.erb
<% content_for(:title, "New Lesson For" + @chapter.name) %>

<h1>New Lesson for <%= @chapter.name %></h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<% content_for(:title, "Chapters | To Do") %>

<h1><%= @lesson.name %></h1>
<h2><%= @lesson.content %></h2>

<%= link_to "Next lesson", chapter_lesson_path(@lesson.next) %>
<%= link_to "Back to Chapter", chapter_lesson(@chapter) %>